### ISSUE TITLE
Vundle

### ISSUE THREAD

**Issue by rkrdo** [jassa/.dotfiles#1]
Cala [vundle](https://github.com/gmarik/Vundle.vim), te va a gustar

**Comment by jassa** [comment]
Gracias :smiley: por ahora dejaré pathogen porque ya quiero programar y no configurar jaja, pero ya vi que una de las utilidades es que no tengo que usar git submodules para llevar track de mis plugins

**Comment by jassa** [comment]
Sólo no me gustó que tiene muchos issues abiertos

**Comment by rkrdo** [comment]
Si, como que no le han dado mucho mantenimiento ultimamente :s pero yo llevo ya mas de un año que me cambie de submodules a Vundle y no he tenido ningun problema, de hecho ayer lo actualice a la version mas reciente jaja pero bueno, saludos Javi!

Por cierto, buena idea eso de separar las configuraciones en archivos, me la voy a copiar :p

**Comment by jassa** [comment]
Jaja sí, casi todos los dotfiles que veo tienen un desmadre, espero que así sean más mantenibles.. saludos :D
